# Generated by Django 4.0.5 on 2022-06-27 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('password_old', models.CharField(blank=True, max_length=100, null=True)),
                ('change_date', models.DateField(blank=True, null=True, verbose_name='date_changed')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_info', models.TextField(blank=True, max_length=250, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='passwords.email')),
            ],
        ),
    ]
