# Generated by Django 4.0.5 on 2022-06-29 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='change_date',
        ),
    ]
